# This is a basic workflow to help you get started with Actions

name: Build Fimware

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
    paths: 'firmware/**'
  pull_request:
    branches: [ main ]
    paths: 'firmware/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Install python 3.x
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'
      # Set the short sha and save it to a global github variable
      - name: get shortsha
        id: vars
        run: |
         echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
      # Install PlatformIO
      - name: Install platformio
        run: |
          set -x
          pip install platformio
          platformio run -d "${GITHUB_WORKSPACE}/firmware"
          mv "${GITHUB_WORKSPACE}/firmware/.pio/build/esp32/firmware.bin" "${GITHUB_WORKSPACE}/${{ steps.vars.outputs.sha_short }}.bin"
      # Upload artifact for further processing
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.vars.outputs.sha_short }}.bin
          path: ./${{ steps.vars.outputs.sha_short }}.bin
