Name: Create release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: get shortsha
        id: vars
        run: |
         echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
      # Install PlatformIO
      - name: Install platformio
        uses: 
          - actions/checkout@v2
          - actions/setup-python@v2
              with:
                python-version: '3.9.0'
        run: |
          set -x
          pip install platformio
          platformio run -d "${GITHUB_WORKSPACE}/firmware"
          mv "${GITHUB_WORKSPACE}/firmware/.pio/build/esp32/firmware.bin" "${GITHUB_WORKSPACE}/${{ steps.vars.outputs.sha_short }}.bin"
      # Upload artifact for further processing
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.vars.outputs.sha_short }}.bin
          path: ./${{ steps.vars.outputs.sha_short }}.bin
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            New release
          draft: false
          prerelease: false
